### ISSUE TITLE
Remove unused input content

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Qualification-CKD#4]
The following files under **Qualification\Input\Content** are not used in the qualification plan and should be removed:
* Concentration_time_profiles.md
* Conclusion.md
* GOF_diagnostics.md
* Input_table.md
* Section2.1_Modeling_Strategy.md
* Section2.2_Data.md
* Section2.3_Model_Parameters_and_Assumptions.md

The following files under **Qualification\Input\Content** are not used in the qualification plan as well. 
Remove? Or will they be included in one of the next versions of the qualificaion plan?
* Gentamicin_CKD.md
* Gentamicin_healthy.md
* Gentamicin_introduction.md
* Pindolol_CKD.md
* Pindolol_healthy.md
* Pindolol_introduction.md
* Sotalol_CKD.md
* Sotalol_healthy.md
* Sotalol_introduction.md
* Vancomycin_CKD.md
* Vancomycin_healthy.md
* Vancomycin_introduction.md

**Comment by msevestre** [comment]
@prvmalik 
What about Gentamicin, Pindolol, Sotalol , Vancomycin?

**Comment by prvmalik** [comment]
They would be inserted if we implemented dialysis. They are not used for this iteration.
