### ISSUE TITLE
Images in report not displayed due to case sensitivity problems

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Qualification-CKD#8]
While the static content images are not copied due to the bug with the brackets in the name - all other images seems to be there.
When I clone the repo locally and open the report e.g. with Typora - the images are properly displayed, e.g.: 

<img width="600" src="https://user-images.githubusercontent.com/25061876/203329233-37b891dd-71af-4699-ba90-c391fd86eab1.png">

But in the online version of the report they are missing.
The problem seems to be the case sensitivity of the image URLs on GitHub

E.g. in the report.md we have 
```
![](images/003_section_compounds/004_section_gabapentin/005_section_gabapentin_healthy/1_time_profile_plot_Gabapentin_Blum_Healthy_400_mg_PO.png)
```

Entering the URL 
```
https://github.com/Open-Systems-Pharmacology/Qualification-CKD/tree/main/Qualification/report/images/003_section_compounds/004_section_gabapentin/005_section_gabapentin_healthy/1_time_profile_plot_Gabapentin_Blum_Healthy_400_mg_PO.png
```
results in 404

Entering the URL 
```
https://github.com/Open-Systems-Pharmacology/Qualification-CKD/blob/main/Qualification/report/images/003_section_Compounds/004_section_Gabapentin/005_section_Gabapentin_Healthy/1_time_profile_plot_Gabapentin_Blum_Healthy_400_mg_PO.png
```
works.

The differences are apparently in the case of the folder names, e.g.
`003_section_compounds` in the **report.md** vs. `003_section_Compounds created` in the Repo.

**Comment by msevestre** [comment]
But those url are generated dynamically...how can we fix this?

**Comment by Yuri05** [comment]
@msevestre Which version of the reporting engine did you use?
@pchelle Any idea, why this happened? Last time when I uploaded a report created with the R-RE it worked: https://github.com/Yuri05/Alfentanil-Model/tree/review/Evaluation/report

and there you can see: the folder names created in the Repo were all lower case:
![grafik](https://user-images.githubusercontent.com/25061876/203335678-764aef7c-00a0-418c-84ae-07701a5ad186.png)

Section references are in both cases (my Alfentanil Report and the CKD report here) all lower case.

**Comment by msevestre** [comment]
In fact, I just updated to the latest released version. I did not have the problem with the previous version  (I think)

**Comment by pchelle** [comment]
Was the reference or id of the section with upper an case at the beginning and then changed ?

Because testing locally, I get exactly the same upper/lower cases in both report and folders.
However, when I update the configuration plan to get lower/upper case but do not delete the previously generated folders, the folder names do not get updated while the paths in the report are updated.

**Comment by msevestre** [comment]
@pchelle 
see https://github.com/Open-Systems-Pharmacology/Qualification-CKD/blob/main/Qualification/Input/qualification_plan.json#L129

**Comment by pchelle** [comment]
Could you send me the zip of the re_input and re_output so I can further investigate ?

**Comment by pchelle** [comment]
Could you also indicate on which system the qualification is running ?
> I suspect the behavior of `dirname()` to be different when copying the figures 
Could you try the code below and let me know if the upper cases appear ?
```r
dirname("images/003_section_compounds/004_section_gabapentin/005_section_gabapentin_healthy/1_time_profile_plot_Gabapentin_Blum_Healthy_400_mg_PO.png")
```

**Comment by msevestre** [comment]
I have deleted everything and recreated everything already.

**Comment by Yuri05** [comment]
the we can close the issue I guess - or are there still any open questions here?

**Comment by msevestre** [comment]
we can close. It does not mean that the issue is solved :)

**Comment by msevestre** [comment]
the way to reproduce is to generate the report again using the branch from a few days ago (where reference and Title were not the same) and see how it behaves
